project_id: '456796'
api_token_env: CROWDIN_API_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    dest: /app/src/main/res/values/strings.xml
    type: android
